2019-12-27 22:11:39,148 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2019-12-27 22:11:39,161 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection("netmiko", task.nornir.config)
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 294, in get_connection
    self.open_connection(
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 345, in open_connection
    self.connections[connection].open(
  File "/usr/lib/python3.8/site-packages/nornir/plugins/connections/netmiko.py", line 58, in open
    self.connection = ConnectHandler(**parameters)
  File "/usr/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 240, in ConnectHandler
    if kwargs["device_type"] not in platforms:
KeyError: 'device_type'

2019-12-27 22:15:33,354 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2019-12-27 22:15:51,725 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show arp'} on 1 hosts
2019-12-27 22:16:08,690 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-27 22:21:22,965 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-27 22:21:22,974 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 49, in napalm_get
    device = task.host.get_connection("napalm", task.nornir.config)
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 294, in get_connection
    self.open_connection(
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 345, in open_connection
    self.connections[connection].open(
  File "/usr/lib/python3.8/site-packages/nornir/plugins/connections/napalm.py", line 49, in open
    network_driver = get_network_driver(platform)
  File "/usr/lib/python3.8/site-packages/napalm/base/__init__.py", line 103, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2019-12-27 22:21:36,731 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-27 22:21:42,058 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-27 22:21:42,074 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 49, in napalm_get
    device = task.host.get_connection("napalm", task.nornir.config)
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 294, in get_connection
    self.open_connection(
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 345, in open_connection
    self.connections[connection].open(
  File "/usr/lib/python3.8/site-packages/nornir/plugins/connections/napalm.py", line 49, in open
    network_driver = get_network_driver(platform)
  File "/usr/lib/python3.8/site-packages/napalm/base/__init__.py", line 103, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2019-12-27 22:23:08,165 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-27 22:23:17,951 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-27 22:23:23,180 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-27 22:23:23,185 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 49, in napalm_get
    device = task.host.get_connection("napalm", task.nornir.config)
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 294, in get_connection
    self.open_connection(
  File "/usr/lib/python3.8/site-packages/nornir/core/inventory.py", line 345, in open_connection
    self.connections[connection].open(
  File "/usr/lib/python3.8/site-packages/nornir/plugins/connections/napalm.py", line 49, in open
    network_driver = get_network_driver(platform)
  File "/usr/lib/python3.8/site-packages/napalm/base/__init__.py", line 103, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: Cannot import "juniper_junos". Is the library installed?

2019-12-27 22:30:32,660 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-27 22:30:37,991 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-27 22:31:21,623 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-27 22:37:52,922 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['cli']} on 1 hosts
2019-12-27 22:37:52,930 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 60, in napalm_get
    method = getattr(device, getter)
AttributeError: 'JunOSDriver' object has no attribute 'get_cli'

2019-12-27 22:38:07,198 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_cli']} on 1 hosts
2019-12-27 22:44:30,164 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['show version']} on 1 hosts
2019-12-27 22:44:34,179 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['show version']} on 1 hosts
2019-12-27 22:44:40,953 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-27 22:44:46,277 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-27 22:44:51,888 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['show version']} on 1 hosts
2019-12-27 22:44:51,896 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 60, in napalm_get
    method = getattr(device, getter)
AttributeError: 'JunOSDriver' object has no attribute 'get_show version'

2019-12-27 22:46:34,911 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['show arp']} on 1 hosts
2019-12-27 22:47:04,652 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-27 22:47:10,075 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['show arp']} on 1 hosts
2019-12-27 22:47:10,570 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 60, in napalm_get
    method = getattr(device, getter)
AttributeError: 'JunOSDriver' object has no attribute 'get_show arp'

2019-12-27 22:54:18,126 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {} on 1 hosts
2019-12-27 22:54:37,494 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['show version']} on 1 hosts
2019-12-27 23:08:15,875 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {} on 1 hosts
2019-12-27 23:08:36,528 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version'} on 1 hosts
2019-12-27 23:08:45,231 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-27 23:09:22,980 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version'} on 1 hosts
2019-12-29 17:59:04,099 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-29 18:00:00,569 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commnds': ['show system processes extensive | match rpd', 'show system processes extensive | match swap']} on 1 hosts
2019-12-29 18:00:00,576 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
TypeError: napalm_cli() got an unexpected keyword argument 'commnds'

2019-12-29 18:00:15,045 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd', 'show system processes extensive | match swap']} on 1 hosts
2019-12-29 18:00:50,634 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd']} on 1 hosts
2019-12-29 18:01:44,698 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd']} on 1 hosts
2019-12-29 18:01:52,358 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd']} on 1 hosts
2019-12-29 18:02:02,210 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version'} on 1 hosts
2019-12-29 18:02:34,632 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd', 'show system processes extensive | match mem']} on 1 hosts
2019-12-29 18:04:47,794 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd', 'show system processes extensive | match mem']} on 1 hosts
2019-12-29 18:04:57,865 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd', 'show system processes extensive | match mem']} on 1 hosts
2019-12-29 18:08:26,040 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'cmd': ['get_facts']} on 1 hosts
2019-12-29 18:08:26,049 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
TypeError: napalm_get() missing 1 required positional argument: 'getters'

2019-12-29 18:08:44,173 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'cmd': ['get_facts']} on 1 hosts
2019-12-29 18:09:17,817 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:09:33,176 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:10:26,089 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:10:33,321 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:11:09,612 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:11:20,747 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:11:30,084 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:11:43,581 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:12:29,519 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:21:49,552 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 1 hosts
2019-12-29 18:28:38,089 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['interfaces']} on 1 hosts
2019-12-29 18:29:35,945 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_bgp']} on 1 hosts
2019-12-29 18:29:35,952 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 60, in napalm_get
    method = getattr(device, getter)
AttributeError: 'JunOSDriver' object has no attribute 'get_bgp'

2019-12-29 18:29:49,048 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['bgp']} on 1 hosts
2019-12-29 18:29:59,239 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['bgp']} on 1 hosts
2019-12-29 18:29:59,744 - nornir.core.task -    ERROR -      start() - Host 'lisbon': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/usr/lib/python3.8/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 60, in napalm_get
    method = getattr(device, getter)
AttributeError: 'JunOSDriver' object has no attribute 'get_bgp'

2019-12-29 18:32:16,866 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['bgp_neighbors']} on 1 hosts
2019-12-29 18:32:28,374 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['bgp_neighbors']} on 1 hosts
2019-12-29 18:37:06,750 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['bgp_neighbors']} on 1 hosts
2019-12-29 18:41:51,856 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary'} on 1 hosts
2019-12-29 18:41:57,084 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd', 'show system processes extensive | match mem']} on 1 hosts
2019-12-29 18:42:02,229 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show system processes extensive | match rpd', 'show system processes extensive | match mem']} on 1 hosts
2019-12-29 18:42:10,666 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['bgp_neighbors']} on 1 hosts
2020-01-01 18:29:19,708 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show bgp summary', 'use_textfsm': True} on 1 hosts
2020-01-01 18:29:44,598 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ospf neighbor', 'use_textfsm': True} on 1 hosts
2020-01-01 18:29:50,753 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ospf neighbor'} on 1 hosts
2020-01-01 18:29:54,675 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ospf neighbor', 'use_textfsm': True} on 1 hosts
2020-01-01 19:15:51,708 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ospf neighbor', 'use_textfsm': True} on 1 hosts
2020-01-01 19:15:58,668 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ospf neighbor', 'use_textfsm': True} on 1 hosts
2020-01-01 19:36:47,231 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show ospf neighbor'} on 1 hosts
